In [8]:
import datetime, os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'
import tensorflow as tf
import numpy as np

In [9]:
work_dir = 'workdir/ex3'
model_dir = work_dir + '/model/'
def TB(external=False):
    from tensorboard import notebook
    notebook.start("--logdir={}".format(model_dir))
    if external:
        import webbrowser
        webbrowser.open("http://localhost:6006")

In [10]:
x_train = np.random.rand(10000, 5)
y_train = np.random.rand(10000, 1)
print(x_train)

[[0.08702655 0.16231424 0.90914226 0.57059855 0.30594149]
 [0.00268278 0.35294878 0.08738262 0.68842675 0.11798177]
 [0.89307955 0.53326627 0.5007021  0.45922428 0.96504087]
 ...
 [0.10681016 0.08622925 0.17949552 0.4815458  0.26143849]
 [0.56967874 0.81397702 0.88824898 0.65939968 0.83572603]
 [0.52101697 0.65267299 0.17760898 0.39320262 0.03457512]]


In [11]:
print(x_train.shape[1:])
feature_columns = [tf.feature_column.numeric_column('x', shape=x_train.shape[1:])]
DNNReg = tf.estimator.DNNRegressor(feature_columns=feature_columns,
                                   model_dir=model_dir,
                                   hidden_units=[500, 300],
                                   optimizer="Adagrad")

(5,)
INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'workdir/ex3/model', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_checkpoint_save_graph_def': True, '_service': None, '_cluster_spec': ClusterSpec({}), '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}


In [12]:
def train_input_fn():
    train_dataset = tf.data.Dataset.from_tensor_slices(
        ({'x': x_train}, y_train)).batch(100)
    return train_dataset

def train_model():
    DNNReg.train(input_fn=train_input_fn, steps=3000)

In [13]:
# Use trusted notebook to display tensorboard inline, otherwise use external=True to open external browser.
TB(external=True)

In [49]:
train_model()

INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 0...
INFO:tensorflow:Saving checkpoints for 0 into workdir/ex3/model/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 0...
INFO:tensorflow:loss = 0.37007794, step = 0
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 100...
INFO:tensorflow:Saving checkpoints for 100 into workdir/ex3/model/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 100...
INFO:tensorflow:Loss for final step: 0.08266407.
